# TorGuard WireGuard Config
[Interface]
PrivateKey = cNeV50RVqGIeRO3Lw+F5Txj7nzj9o3Sl0Q4W7huaL2c=
ListenPort = 55623
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.62.141/24

[Peer]
PublicKey = kby+ggANdIIxbzHIcChONGa2SiedA0KguKXnsfAUiyY=
AllowedIPs = 0.0.0.0/0
Endpoint = 31.40.212.70:1443
PersistentKeepalive = 25