# TorGuard WireGuard Config
[Interface]
PrivateKey = WKISZfkZsAuXL4XNWN6vbAuWnOZh+9SoyaFLJL6Vb18=
ListenPort = 59704
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.25.205/24

[Peer]
PublicKey = cMcjs1Z1fUlz92MgeXoGkoGLjtc2cb0eiIh5Mo19zCQ=
AllowedIPs = 0.0.0.0/0
Endpoint = 37.120.155.18:1443
PersistentKeepalive = 25