# TorGuard WireGuard Config
[Interface]
PrivateKey = IKlHyXSw7QRIT75iCKSCNyDNjWYZr7WU7Uy6R5eX1VA=
ListenPort = 59852
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.59.201/24

[Peer]
PublicKey = Wuy/wQ+rOX3QEgb0dKIbzeRF9BW06eX6s7OUFWP38Qw=
AllowedIPs = 0.0.0.0/0
Endpoint = 146.70.137.42:1443
PersistentKeepalive = 25