# TorGuard WireGuard Config
[Interface]
PrivateKey = iKXsQOQADgokndAkb+VYO6VOOskUywM/2bZlC++e2FE=
ListenPort = 55186
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.42.221/24

[Peer]
PublicKey = Bw/Rcm5radzK2U/n+DtS5/iE7NUnEjrCJqwuYqJyJF0=
AllowedIPs = 0.0.0.0/0
Endpoint = 134.195.197.77:1443
PersistentKeepalive = 25