# TorGuard WireGuard Config
[Interface]
PrivateKey = sITgUALaCsnv9/DQNruEBJhzR8AZaZ0Z8ss7ZH26gEE=
ListenPort = 60338
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.26.81/24

[Peer]
PublicKey = FZEUfioJV4E3GN+I7K7yV81S826/e4uIeg5HbUYinUI=
AllowedIPs = 0.0.0.0/0
Endpoint = 45.12.221.2:1443
PersistentKeepalive = 25