# TorGuard WireGuard Config
[Interface]
PrivateKey = 8Pd0L48Y0k75rukpzH6guDCu8kCHwYtGBSkfnpO0KmA=
ListenPort = 58748
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.121.61/24

[Peer]
PublicKey = YAQPYW1ipAxIXSNjr88WpU7OMkx/WthX97U2uWVS2EA=
AllowedIPs = 0.0.0.0/0
Endpoint = 91.132.197.186:1443
PersistentKeepalive = 25