# TorGuard WireGuard Config
[Interface]
PrivateKey = ABid9WUr/N8giLYNU9mw0UCVBc3Un6hA8HfpX6lXLWY=
ListenPort = 55332
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.88.41/24

[Peer]
PublicKey = goW2EjvR0yQFwzGHFKLRwOpeLK+bgS5W8wHrWP+QSjY=
AllowedIPs = 0.0.0.0/0
Endpoint = 95.174.67.130:1443
PersistentKeepalive = 25