# TorGuard WireGuard Config
[Interface]
PrivateKey = IG+AFm5ivZzShsembn5EfJxi6tEx5sdm+xqIrYl3nls=
ListenPort = 56071
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.13.221/24

[Peer]
PublicKey = +y2zVEswof1ALeP7zLgchoC6l/9ocoPRsf6bgT/4qXQ=
AllowedIPs = 0.0.0.0/0
Endpoint = 193.56.253.82:1443
PersistentKeepalive = 25